var dms={today:new Date(),startOfEpoch:new Date(0),tz:moment.tz.guess(),fmtStr:'ddd MMM D YYYY HH:mm:ss [GMT]ZZ',tzOptions:[]};dms.todayStr=moment.tz(dms.today,dms.tz).format(dms.fmtStr);dms.startOfEpochStr=moment.tz(dms.startOfEpoch,dms.tz).format(dms.fmtStr);jQuery.each(moment.tz.names(),function(index,value){dms.tzOptions.push({value:readableTimeZone(value),data:value});});jQuery('.your-computers-time').html(dms.todayStr+' ('+dms.tz+')');jQuery('.your-computers-ms').html(dms.today.valueOf());jQuery('.your-tz').html(dms.tz);jQuery('.start-of-epoch').html(dms.startOfEpochStr);jQuery('#d2mBtnId').html("converted to milliseconds<br />since the start of Unix Epoch Time<br />"+dms.startOfEpochStr);var tzSelect=jQuery('.timezone-selector');tzSelect.autocomplete({lookup:dms.tzOptions,onSelect:function(suggestion){jQuery(this).attr('data-tz',suggestion.data);var callback=this.dataset.callback;window[callback](this.form);},onInvalidateSelection:function(){this.form.output.value='Please correct the timezone.'},autoSelectFirst:true,showNoSuggestionNotice:true,noSuggestionNotice:'No matching time zone.'});tzSelect.val(readableTimeZone(dms.tz));tzSelect.attr('data-tz',dms.tz);tzSelect.click(function(){jQuery(this).select();});jQuery('.useDatePicker').datetimepicker();function readableTimeZone(str){return str.replace(/_/g,' ');}
function msConverter(inPut,operand,tmpU,inMS){var ms=inMS?1000:1;var factors="";switch(tmpU)
{case "ms":factors=1;break;case "sec":factors=ms;break;case "min":factors=60*ms;break;case "hours":factors=60*60*ms;break;case "days":factors=60*60*24*ms;break;case "weeks":factors=60*60*24*7*ms;break;case "months":factors=60*60*24*31*ms;break;case "years":factors=60*60*24*365*ms;break;}
return eval(inPut+operand+factors);}
function secToCal(f){var inPut=parseInt(f.inPut.value)?parseInt(f.inPut.value):0;var tmpU=f.tmpUnit.options[f.tmpUnit.selectedIndex].value;if(!tmpU)return;f.output.value=msConverter(inPut,"/",tmpU,f.milli.checked);ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'milliseconds-converted-to-a-temporal-value',eventLabel:inPut});}
function TemporalUnitToMS(f){var inPut=parseInt(f.inPut.value)?parseInt(f.inPut.value):0;var tmpU=f.tmpUnit.options[f.tmpUnit.selectedIndex].value;if(!tmpU)return;f.output.value=msConverter(inPut,"*",tmpU,f.milli.checked)
ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'temporal-value-converted-to-milliseconds',eventLabel:inPut});}
function stringToNum(f){if(!f.inPut.value.length){alert("Please enter a date string first.");return;}
f.output.value=Date.parse(f.inPut.value);ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'date-to-milliseconds-converter',eventLabel:f.inPut.value});}
function secToCalQC(f){if(f.output.value!=""){if(f.milli.checked)f.output.value=f.output.value/1000;else f.output.value=f.output.value*1000;}}
function addToToday(f){todayMS=dms.today.valueOf();var inPut=parseInt(f.inPut.value)?parseInt(f.inPut.value)*(f.milli.checked?1:1000):0;if(!inPut)return;var mathString=todayMS+f.operand.value+inPut;var futureDate=new Date(eval(mathString));f.output.value=futureDate;}
function howFarCal(f){if(!f.inPut.value.length){return;}
var inPut=Date.parse(f.inPut.value);if(isNaN(inPut)){return;}
todayMS=dms.today.valueOf();var outPut=Math.abs(todayMS-inPut);var tmpU=f.tmpUnit.options[f.tmpUnit.selectedIndex].value;if(!tmpU)return;f.output.value=msConverter(outPut,"/",tmpU,true);ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'how-much-time-between-now-and-then',eventLabel:f.inPut.value});}
function howFarMS(f){if(!f.inPut.value.length)return;todayMS=dms.today.valueOf();var mx=f.milli.checked?1:1000;var inPut=parseInt(f.inPut.value)?(parseInt(f.inPut.value)*mx):false;if(!inPut)return;var outPut=Math.abs(todayMS-inPut);var tmpU=f.tmpUnit.options[f.tmpUnit.selectedIndex].value;if(!tmpU)return;f.output.value=msConverter(outPut,"/",tmpU,true);ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'how-many-milliseconds-between-now-and-then',eventLabel:inPut});}
function timeToDate(f){if(!f.inPut.value.length){f.output.value="";return;}
var selectedTZ=f.TZ.dataset.tz;if(dms.tz==selectedTZ){f.output.value=moment.tz(new Date(parseInt(f.inPut.value)*(f.milli.checked?1:1000)),dms.tz);}else{var localDate=moment.tz(new Date(parseInt(f.inPut.value)*(f.milli.checked?1:1000)),dms.tz);f.output.value=localDate.clone().tz(selectedTZ);}
ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'millisecond-to-date-string',eventLabel:f.output.value});}
function whatIsThatDate(f){var tmpU=f.tmpUnit.options[f.tmpUnit.selectedIndex].value;if(!tmpU.length)return;if(!f.inPut.value.length){f.output.value="";return;}
if(isNaN(parseInt(f.inPut.value))){alert("Sorry, you need to enter an integer to complete this calculation.");return;}
var inPut=msConverter(f.inPut.value,"*",tmpU,true);todayMS=dms.today.valueOf();var mathString=todayMS+f.operand.value+inPut;var resultingDate=new Date(eval(mathString));f.output.value=resultingDate;ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'what-date-would-that-be',eventLabel:f.output.value});}
var inputDateFormat='YYYY/MM/DD HH:mm',outputDateFormat='YYYY/MM/DD HH:mm:ss.SSS';function dateMath(f){var augend=f.augend.value,augendTZ=f.augendTZ.dataset.tz,outputTZ=f.outputTZ.dataset.tz;if(!augend)return;augend=moment.tz(augend,inputDateFormat,augendTZ);if(f.operand.value=='+'){augend.add(f.addend.value,f.tmpUnit.value);}else{augend.subtract(f.addend.value,f.tmpUnit.value);}
f.output.value=augend.tz(outputTZ).format(outputDateFormat);ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'dateMath',eventLabel:augendTZ+' | '+f.output.value+' | '+outputTZ});}
function dateSubtraction(f){var minuend=f.minuend.value,minuendTZ=f.minuendTZ.dataset.tz,subtrahend=f.subtrahend.value,subtrahendTZ=f.subtrahendTZ.dataset.tz;if(!subtrahend||!minuend)return;minuend=moment.tz(minuend,inputDateFormat,minuendTZ);subtrahend=moment.tz(subtrahend,inputDateFormat,subtrahendTZ);f.output.value=minuend.diff(subtrahend,f.tmpUnit.value,true);ga('send',{hitType:'event',eventCategory:'dateCalculators',eventAction:'dateSubtraction',eventLabel:minuendTZ+' | '+f.output.value+' | '+subtrahendTZ});}